### ISSUE TITLE
createFromTransaction TestCases

### ISSUE THREAD

**Issue by hugo-dc** [ewasm/tests#15]
Write more test cases for creating contracts from transaction:
current test case `createFromTransaction` only tests when returning ewasm, test other cases:
- [x] returning 2 bytes EVM code
- [x] returning 0 bytes
- [x] returning random bytes
- [x] code size is greater than max code size
- [x] the cost of the new code creation is greater than gas limit

**Comment by lrettig** [comment]
Closing as #35 was merged
