### ISSUE TITLE
Interface test implementation progress

### ISSUE THREAD

**Issue by jwasinger** [ewasm/tests#3]
WIP

Working branch on https://github.com/ewasm/tests#wasm-tests

@hugo-dc: 
 - [x] getAddress
- [x] getBlockHash (should this be a Blockchain test?)
- [x]  getCaller
- [x]  getCodeSize
- [x]  getBlockDifficulty (should this be a Blockchain test?)
- [x]  getGasLeft
- [x]  getBlockNumber (should this be a Blockchain test?)
- [x]  selfDestruct
- [x]  callDelegate
- [x] callStatic

@jwasinger:
- [x] useGas
- [x]  getCallDataSize
- [x] getBalance:
  * [x] get balance of currently-executing account
  * [x] get balance of another account
- [x]  call
- [x]  storageLoad
- [x]  codeCopy
- [x]  externalCodeCopy
- [x]  getBlockGasLimit (should this be a Blockchain test?)
- [x]  getTxGasPrice (should this be a Blockchain test?)
- [x]  getTxOrigin (should this be a Blockchain test?)
- [x]  getBlockTimestamp (should this be a Blockchain test?)
- [x]  return
- [x]  create

@lrettig:
- [x]  callDataCopy
- [x]  callCode
- [x]  storageStore
- [x]  getCallValue
- [x]  getBlockCoinbase (should this be a Blockchain test?)
- [x]  getExternalCodeSize 
- [x]  revert
- [x]  getReturnDataSize
- [x]  returnDataCopy
- [x]  createFromTransaction
- [ ]  log

**Comment by axic** [comment]
> get balance of another account (broken)

Still don't get why this would be broken? Where is the test case?

**Comment by jwasinger** [comment]
It's not..  I just forgot to update the comment before copy-pasting it directly from https://github.com/ethereum/tests/pull/394

**Comment by lrettig** [comment]
These are done, except for log. Closing in favor of #11.
