### ISSUE TITLE
OOB memory access test cases

### ISSUE THREAD

**Issue by jwasinger** [ewasm/tests#34]
As we are deviating from EVM1 with regards to how the EEI treats reads from OOB memory (see https://github.com/ewasm/hera/pull/222), we need test cases that capture this spec change.

`externalCodeCopy`, `codeCopy` and `returnDataCopy` need to have test cases to make sure that: copying from OOB memory traps.

Cf: https://github.com/ewasm/evm2wasm/issues/250

**Comment by lrettig** [comment]
I'm confused. The EVM behavior, and the behavior of existing clients, is not to trap but instead to just fill in the memory with zeroes as you suggested in https://github.com/ewasm/hera/issues/221. If Hera exhibits different behavior then existing EVM tests will fail. Which behavior should we be testing for?

In particular, since Hera traps, all remaining gas gets consumed, which is not what EVM does.

CC @jwasinger @axic

**Comment by cdetrio** [comment]
EVM behavior of RETURNDATACOPY is different from CALLDATACOPY. callDataCopy will copy zero bytes if given offsets beyond the calldata size. RETURNDATACOPY will throw an exception:

https://github.com/ethereum/EIPs/blob/06df3ce690e5c214e02d720658cd2b326f1db6cc/EIPS/eip-211.md

> This opcode has similar semantics to CALLDATACOPY, but instead of copying data from the call data, it copies data from the return data buffer. Furthermore, accessing the return data buffer beyond its size results in a failure; i.e. if start + length overflows or results in a value larger than RETURNDATASIZE, the current call stops in an out-of-gas condition. In particular, reading 0 bytes from the end of the buffer will read 0 bytes; reading 0 bytes from one-byte out of the buffer causes an exception.

**Comment by lrettig** [comment]
So we want to match the EVM behavior here as well, right?

**Comment by lrettig** [comment]
It looks like codecopy and extcodecopy do not trap, only returndatacopy. I'll add tests for all of this expected behavior.

**Comment by lrettig** [comment]
I'm still a little confused by @axic's comments in https://github.com/ewasm/hera/pull/222:

> I think we tried to break away from that EVM nonsense in ewasm

Are we mimicking EVM behavior as discussed in this thread or are we "breaking away"? And if so what does that mean?

**Comment by axic** [comment]
> It looks like codecopy and extcodecopy do not trap, only returndatacopy. I'll add tests for all of this expected behavior.
> So we want to match the EVM behavior here as well, right?

Yes, the idea would be to do copy the logic from `returndatacopy`. That is a small improvement we can make over EVM :)

Though the test cases should match what Hera is doing and then we can change Hera. That change should trigger a test failure (showing that the tests indeed are useful) and we can adjust them.
