### ISSUE TITLE
more testing around create / call*

### ISSUE THREAD

**Issue by jwasinger** [ewasm/tests#39]
From @axic : 

> https://github.com/ewasm/tests/blob/wasm-tests/src/GeneralStateTestsFiller/stEWASMTests/createFiller.yml#L29
This is the culprit.
The only native create test we have creates a contract of 0 bytes.
The interface of creation is never tested properly, because apparently there is no need for tests.

**Comment by axic** [comment]
The same problem appears to be present with `call*`.
