### ISSUE TITLE
Test case for validating ECI: contract with start defined

### ISSUE THREAD

**Issue by axic** [ewasm/tests#53]
It should be rejected.

**Comment by lrettig** [comment]
Can you elaborate? What's an ECI contract and why is this an error?

**Comment by axic** [comment]
["ECI"](https://github.com/ewasm/design/blob/master/contract_interface.md)

The start method is executed upon loading. There is no time to interact with the memory before that as a result it is not possible to implement ewasm-kernel in Javascript. Instead, we disallow the start method and define that `main` will be called after loading.

This may have changed since in the Javascript API, but this is the spec at the moment.

**Comment by axic** [comment]
This is part of the test matrix, named `hasStartDeclared`

**Comment by axic** [comment]
This is now being addressed by new tests (also it is in the test matrix).
