### ISSUE TITLE
Fill Blockchain Tests

### ISSUE THREAD

**Issue by jwasinger** [ewasm/tests#84]

**Comment by axic** [comment]
What is this exactly about?

**Comment by lrettig** [comment]
Was this about refilling the tests? I think @hugo-dc did this a week or so ago already right? @jwasinger can we close?

**Comment by jwasinger** [comment]
No.  it's about filling and running the tests as blockchain tests.  Can't think of what tangible value that brings outside of allowing us to use hive for testing.

**Comment by axic** [comment]
@jwasinger is this just a matter of running testeth to do it or does it require any other work?

**Comment by jwasinger** [comment]
There's a testeth option to fill blockchain tests.

I think this should be closed.  state tests are fine imo.
