### ISSUE TITLE
Some missing tests based on code coverage

### ISSUE THREAD

**Issue by axic** [ewasm/tests#85]
- ~~selfdestruct to a non-existent account~~
- ~~call/create sending stipend, where the sender account's balance in the state exceeds 128bits~~
- ~~call/create return empty data~~
- ~~call/create call depth (1024) exceeded~~
- ~~call with value transfer to a non-existent account~~
- ~~call with empty value~~ @jakelang checked this, and it is about callcode with empty value
- ~~create with not enough value~~ [#90]
- ~~create failing (e.g. with unreachable)~~
- ~~create failing and returning data (e.g. with revert)~~ [in #68]
- blockhash returning empty blockhash vs. non-empty blockhash (not sure which one is missing)

**Comment by hugo-dc** [comment]
@axic I have some questions about the test cases:
- call/create sending stipend, where the sender account's balance in the state exceeds 128bits: here I have to call `create` or `call` sending a value, and set the sender balance to a number which exceeds 128 bits, is that correct?
- call with empty value -this is not covered by the existing test case [callNoDataNoValue ](https://github.com/ewasm/tests/blob/wasm-tests/src/GeneralStateTestsFiller/stEWASMTests/callNoDataNoValueFiller.yml)?
- blockhash returning empty blockhash: we currently have blockhash test cases, one of them try to get the blockhash for the current block, then getBlockHash returns nothing and results in failure, and there is another test case which successfully returns the blockhash of previous block, could you clarify what is needed?

**Comment by axic** [comment]
> call/create sending stipend, where the sender account's balance in the state exceeds 128bits:

The balance in the "genesis" has to exceed it, before you start the transaction.

> call with empty value -this is not covered by the existing test case callNoDataNoValue ?

Apparently it isn't according to codecov, we need to investigate.

> blockhash returning empty blockhash: we currently have blockhash test cases, one of them try to get the blockhash for the current block, then getBlockHash returns nothing and results in failure, 

Again apparently according to codecov that is not covered.

**Comment by hugo-dc** [comment]
thanks for your comments, I will take a look

**Comment by hugo-dc** [comment]
@axic I checked the codecov report.
For both cases, call and blockhash, the not fully covered code are if statements marked in yellow, those if statements are marked as yellow because doesn't have an `else`. But you can see that the following statement inside the if's are green

**Comment by axic** [comment]
@hugo-dc there are two cases above not stricken through, are those still missing?

**Comment by hugo-dc** [comment]
@axic I think both are covered by existing test cases, there are some if statements marked as yellow by codecov, but this is because those if statements doesn't have an else part.

**Comment by axic** [comment]
There was another list: https://github.com/ewasm/hera/issues/399

**Comment by axic** [comment]
> blockhash returning empty blockhash vs. non-empty blockhash (not sure which one is missing)

`getBlockHash` and `getBlockHashFailure` should cover these
