### ISSUE TITLE
memory 100 in storedMalformedBytecodeHasStartFromTxFiller

### ISSUE THREAD

**Issue by lrettig** [ewasm/tests#98]
https://github.com/ewasm/tests/blob/33954722f73c09db6797e78b2fd203d14b757f16/src/GeneralStateTestsFiller/stEWASMTests/storedMalformedBytecodeHasStartFromTxFiller.yml#L58

@hugo-dc why did you use `memory 100` here instead of `memory 1`?

**Comment by hugo-dc** [comment]
@lrettig no particular reason, I took that wast code from somewhere else, it can/should be changed to `(memory 1)`.
